spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        enable-api: true
        name: demo
        namespace: default
        sources:
          - name: demo1
            namespace: test
          - name: demo2
            namespace: develop
