spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        enable-api: true
        sources:
          - name: demo
            namespace: default
          - name: demo1
            namespace: test
          - name: demo2
            namespace: develop
